import { FileText } from 'lucide-react';
import { useTheme } from '../hooks/useTheme';
import { FadeIn } from '../components/AnimationWrappers';
import PublicLayout from '../layouts/PublicLayout';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using QuickRaina ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, please do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.`,
  },
  {
    title: '2. Description of Service',
    content: `QuickRaina is an AI-powered dream visualization platform that allows users to describe their dreams in natural language and receive AI-generated visual interpretations. The Service includes the website, mobile interfaces, APIs, and any related products or services offered by QuickRaina Inc.`,
  },
  {
    title: '3. User Accounts',
    content: `To access certain features, you must create an account. You are responsible for:

• Maintaining the confidentiality of your account credentials.
• All activities that occur under your account.
• Providing accurate and up-to-date information.
• Immediately notifying us of any unauthorized use of your account.

You must be at least 13 years of age to use the Service.`,
  },
  {
    title: '4. Acceptable Use',
    content: `You agree not to:

• Use the Service for any unlawful or fraudulent purpose.
• Submit content that is harmful, abusive, threatening, defamatory, or violates any third-party rights.
• Attempt to reverse engineer, decompile, or extract source code from our AI models or platform.
• Use automated tools to scrape, crawl, or overload our systems.
• Share, sell, or sublicense your account access to third parties.
• Submit deliberately false or misleading dream content to manipulate the AI.`,
  },
  {
    title: '5. Intellectual Property',
    content: `**Your Content**: You retain ownership of the dream descriptions you provide. By submitting content, you grant QuickRaina a limited, non-exclusive license to process and generate visualizations from your content.

**Generated Images**: Images generated by QuickRaina from your descriptions are licensed to you for personal use. Luminary plan subscribers receive a commercial usage license as described in their plan details.

**Our Property**: The QuickRaina platform, design, AI models, and brand are owned by QuickRaina Inc. and protected by applicable intellectual property laws.`,
  },
  {
    title: '6. Payment & Subscriptions',
    content: `Paid plans are billed on a monthly or annual basis. By subscribing, you authorize us to charge your payment method on a recurring basis. Subscriptions automatically renew unless cancelled before the renewal date. Refunds are available within 14 days of initial purchase if you are unsatisfied with the Service.`,
  },
  {
    title: '7. Disclaimers',
    content: `The Service is provided "as is" without warranties of any kind. QuickRaina does not guarantee that:

• The Service will be uninterrupted or error-free.
• AI-generated visualizations will accurately represent your experiences.
• The Service will meet all of your requirements.

Dream interpretations and visualizations are for creative and entertainment purposes only and do not constitute psychological or medical advice.`,
  },
  {
    title: '8. Limitation of Liability',
    content: `To the maximum extent permitted by law, QuickRaina shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the Service. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: '9. Termination',
    content: `We reserve the right to suspend or terminate your account at our discretion if you violate these Terms or engage in behavior that harms the platform, other users, or our team. You may also delete your account at any time from your account settings.`,
  },
  {
    title: '10. Changes to Terms',
    content: `We may update these Terms from time to time. Material changes will be communicated via email or an in-app notice at least 14 days in advance. Continued use of the Service after changes constitutes acceptance.`,
  },
  {
    title: '11. Contact',
    content: `For questions about these Terms, contact us at:\n\nlegal@quickraina.ai\n\nQuickRaina Inc., 123 Dream Lane, San Francisco, CA 94105`,
  },
];

export default function TermsOfService() {
  const { dark } = useTheme();

  return (
    <PublicLayout>
      <section className="pt-32 pb-16 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[400px] bg-violet-600/10 blur-[120px] rounded-full pointer-events-none" />
        <div className="max-w-3xl mx-auto px-4 text-center relative">
          <FadeIn>
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 flex items-center justify-center mx-auto mb-6">
              <FileText className="w-7 h-7 text-white" />
            </div>
            <h1 className={`font-display text-5xl sm:text-6xl font-bold mb-6 ${dark ? 'text-white' : 'text-slate-900'}`}>
              Terms of <span className="gradient-text">Service</span>
            </h1>
            <p className={`text-base ${dark ? 'text-slate-500' : 'text-slate-400'}`}>
              Last updated: April 19, 2026
            </p>
            <p className={`text-xl leading-relaxed mt-4 ${dark ? 'text-slate-400' : 'text-slate-600'}`}>
              Please read these terms carefully before using QuickRaina.
            </p>
          </FadeIn>
        </div>
      </section>

      <section className="pb-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-8">
            {sections.map(({ title, content }, i) => (
              <FadeIn key={title} delay={i * 0.05}>
                <div className={`p-8 rounded-2xl border ${dark ? 'bg-[#12121a] border-white/8' : 'bg-white border-slate-200 shadow-sm'}`}>
                  <h2 className={`font-display text-xl font-bold mb-4 ${dark ? 'text-white' : 'text-slate-900'}`}>{title}</h2>
                  <div className={`text-sm leading-relaxed whitespace-pre-line ${dark ? 'text-slate-400' : 'text-slate-600'}`}>
                    {content}
                  </div>
                </div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
